AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HelloBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
        IndexDocument: index.html
        ErrorDocument: error.html
  HelloFunction:
    Type: "AWS::Lambda::Function"
    Properties: 
      Code:
        